#!groovy

def name = 'watermark'
def app
def pathToCi = "${name}/ci"
def dockerfile= 'dockerfile'

def getUserUid() {
    return sh(returnStdout: true, script: 'id -u').trim()
}

def build(name, file = "${pathToCi}/${dockerfile}", customParams = '') {
    return docker.build("$name-test", "--build-arg uid=${getUserUid()} -f $file")
}

node {
    stage ('Checkout'){
        checkout scm
    }

    stage ('Build docker environment'){
        sh "ls ${pathToCi}"
        sh "building"
        app = build(name)
    
    }
/*
    stage ('Building'){
        app.inside {
            sh "echo Building"
            sh "rustc --version"
        }
    }

    stage ('Testing'){
        sh "echo Testing"
        sh "cd ${name}"
        sh "ls"
    }
*/
}


