#!groovy

def app
def pathToCi = 'watermark/ci'
def dockerfile= 'dockerfile'

def getUserUid() {
    return sh(returnStdout: true, script: 'id -u').trim()
}

def build(name, file = 'watermark/ci/ubuntu.dockerfile watermark/ci', customParams = '') {
    return docker.build("$name-test", "--build-arg uid=${getUserUid()} -f $file")
}

node {
    stage ('Checkout'){
        checkout scm
    }

    stage ('Build docker environment'){
        sh "pwd"
        sh "ls ${pathToCi}"
        sh "echo building"
        app = build('watermark')
    
    }
    stage ('Building'){
        //TODO: Fix this
        app.inside {
            sh "rustc --version"
        }
    }

    stage ('Testing'){
        sh "echo Testing"
        app.inside {
            sh "cd watermark; pwd; ls; cargo test"
        }
    }
}


