#!groovy

def getUserUid() {
    return sh(returnStdout: true, script: 'id -u').trim()
}

def build(name, file = 'watermark/ci/dockerfile ci', customParams = '') {
    return docker.build("$name-test", "--build-arg uid=${getUserUid()} -f $file")
}

def name = 'watermark'
def app
node {
    stage ('Checkout'){
        checkout scm
    }

    stage ('Build docker environment'){
        app = build(name)
    
    }
    stage ('Building'){
        app.inside {
            sh "echo Building"
            sh "rustc --version"
        }
    }

    stage ('Testing'){
        sh "echo Testing"
        sh "cd ${name}"
        sh "ls"
    }
}


