use super::ErrorCode;
use std::os::raw::c_char;

extern {
    #[no_mangle]
    pub fn indy_register_payment_method(
        command_handle: i32,
        payment_method: *const c_char,

        create_payment_address: Option<extern fn(_command_handle: i32,
                                                 config: *const c_char,
                                                 _cb: Option<extern fn(command_handle_: i32,
                                                                       err: ErrorCode,
                                                                       payment_address: *const c_char) -> ErrorCode>) -> ErrorCode>,
        add_request_fees: Option<extern fn(_command_handle: i32,
                                           _wallet_handle: i32,
                                           req_json: *const c_char,
                                           inputs_json: *const c_char,
                                           outputs_json: *const c_char,
                                           _cb: Option<extern fn(command_handle_: i32,
                                                                 err: ErrorCode,
                                                                 req_with_fees_json: *const c_char) -> ErrorCode>) -> ErrorCode>,
        parse_response_with_fees: Option<extern fn(_command_handle: i32,
                                                   resp_json: *const c_char,
                                                   _cb: Option<extern fn(command_handle_: i32,
                                                                         err: ErrorCode,
                                                                         utxo_json: *const c_char) -> ErrorCode>) -> ErrorCode>,
        build_get_utxo_request: Option<extern fn(_command_handle: i32,
                                                 _wallet_handle: i32,
                                                 payment_address: *const c_char,
                                                 _cb: Option<extern fn(command_handle_: i32,
                                                                       err: ErrorCode,
                                                                       get_utxo_txn_json: *const c_char) -> ErrorCode>) -> ErrorCode>,
        parse_get_utxo_response: Option<extern fn(_command_handle: i32,
                                                  resp_json: *const c_char,
                                                  _cb: Option<extern fn(command_handle_: i32,
                                                                        err: ErrorCode,
                                                                        utxo_json: *const c_char) -> ErrorCode>) -> ErrorCode>,
        build_payment_req: Option<extern fn(_command_handle: i32,
                                            _wallet_handle: i32,
                                            inputs_json: *const c_char,
                                            outputs_json: *const c_char,
                                            _cb: Option<extern fn(command_handle_: i32,
                                                                  err: ErrorCode,
                                                                  payment_req_json: *const c_char) -> ErrorCode>) -> ErrorCode>,
        parse_payment_response: Option<extern fn(_command_handle: i32,
                                                 resp_json: *const c_char,
                                                 _cb: Option<extern fn(command_handle_: i32,
                                                                       err: ErrorCode,
                                                                       utxo_json: *const c_char) -> ErrorCode>) -> ErrorCode>,
        build_mint_req: Option<extern fn(_command_handle: i32,
                                         _wallet_handle: i32,
                                         outputs_json: *const c_char,
                                         _cb: Option<extern fn(command_handle_: i32,
                                                               err: ErrorCode,
                                                               mint_req_json: *const c_char) -> ErrorCode>) -> ErrorCode>,
        build_set_txn_fees_req: Option<extern fn(_command_handle: i32,
                                                 _wallet_handle: i32,
                                                 fees_json: *const c_char,
                                                 _cb: Option<extern fn(command_handle_: i32,
                                                                       err: ErrorCode,
                                                                       set_txn_fees_json: *const c_char) -> ErrorCode>) -> ErrorCode>,
        build_get_txn_fees_req: Option<extern fn(_command_handle: i32,
                                                 _wallet_handle: i32,
                                                 _cb: Option<extern fn(command_handle_: i32,
                                                                       err: ErrorCode,
                                                                       get_txn_fees_json: *const c_char) -> ErrorCode>) -> ErrorCode>,
        parse_get_txn_fees_response: Option<extern fn(_command_handle: i32,
                                                      resp_json: *const c_char,
                                                      _cb: Option<extern fn(command_handle_: i32,
                                                                            err: ErrorCode,
                                                                            fees_json: *const c_char) -> ErrorCode>) -> ErrorCode>,

        cb: Option<extern fn(command_handle_: i32, err: ErrorCode)>) -> ErrorCode;

    #[no_mangle]
    pub fn indy_build_get_txn_request(command_handle: i32,
                                      submitter_did: *const c_char,
                                      seq_no: i32,
                                      cb: Option<extern fn(xcommand_handle: i32, err: ErrorCode,
                                                           request_json: *const c_char)>) -> ErrorCode;

}