source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/evernym/sovrin-client-ios.git'
platform :ios, '10.2'
#use_frameworks!

def appPods
    pod 'milagro'
end

target 'milagro-test-app' do
    project 'milagro-test-app'
    appPods
end

# ignore all warnings from all pods
#inhibit_all_warnings!

workspace './milagro-test-app.xcworkspace'

# ignore all warnings from all pods
#inhibit_all_warnings!

post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'milagro'
        target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'AMCL_VERSION_MAJOR=3 AMCL_VERSION_PATCH=0 AMCL_VERSION_MINOR=0 OS=\"IOS\"']
        end
      end
    end
end

