# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"


gem "cocoapods-downloader", "= 1.2.2"

gem "cocoapods", "~> 1.5"
