[package]
name = "issue-credential"
version = "0.1.0"
authors = ["matt raffel <matt.raffel@evernym.com>"]

[[bin]]
name = "issue-credential"
path = "src/issue-credential.rs"

[[bin]]
name = "template"
path = "src/template.rs"

[dependencies]
indy = "1.6.7"
lazy_static = "0.2"
log = "0.4.1"
log-panics = "2.0.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
