# Development
FROM libindy

ARG uid=1000

RUN apt-get update && apt-get install -y python3

RUN apt-get install -y python3-pip

RUN pip3 install pytest qrcode pytest-asyncio

ENV PYTHONPATH=$PYTHONPATH:/python3

RUN mkdir -p /scripts
COPY ci/scripts/ /scripts

COPY libvcx/target/debug/libvcx.so /usr/lib
COPY wrappers/python3/ /python3
WORKDIR /python3/tests

CMD [ "/usr/bin/python3", "-m", "pytest", "-v"]

