@startuml

[*] --> ProposalSent : Send Proposal
[*] --> ProposalSent : Offer negotiated
[*] --> RequestSent : Offer accepted
[*] --> RequestSent : Request Sent
[*] --> [*] : Offer rejected
ProposalSent --> RequestSent : Offer Accepted
ProposalSent --> ProposalSent : Offer Negotiated
ProposalSent --> [*] : Offer Rejected
RequestSent --> [*] : Request Rejected
RequestSent --> [*] : Credential acked

@enduml