@startuml

[*] --> OfferSent : Init by Issuer
[*] --> OfferSent : Proposal negotiated
OfferSent --> [*] : Offer Rejected
OfferSent --> [*] : Proposal rejected
OfferSent --> OfferSent : Proposal negotiated
OfferSent --> CredentialSent : Request received
CredentialSent --> [*] : Credential acked
[*] --> [*] : Proposal rejected

@enduml