@startuml

[*] --> OfferSent : Init by Issuer
OfferSent --> [*] : Offer Rejected
OfferSent --> [*] : Proposal rejected
OfferSent --> CredentialSent : Request received
CredentialSent --> [*] : Credential acked
[*] --> [*] : Proposal rejected

@enduml