@startuml
title Credential Issuance State Machine

state Issuer {
    [*] --> IssuerInitialized

    state "Initialized" as IssuerInitialized

    state IssuerCheckTransitionToOfferCreated <<choice>>

    note left of IssuerCheckTransitionToOfferCreated :  if transition allowed?

    IssuerInitialized -down-> IssuerCheckTransitionToOfferCreated: cred offer
    IssuerCheckTransitionToOfferCreated -down-> OfferCreated: ok: step(cred offer)
    IssuerCheckTransitionToOfferCreated -up-> IssuerInitialized: no

    state OfferCreated: cred offer

    state IssuerCheckTransitionToOfferSent <<choice>>

    note left of IssuerCheckTransitionToOfferSent :  if transition allowed?

    OfferCreated --> IssuerCheckTransitionToOfferSent: response
    IssuerCheckTransitionToOfferSent --> OfferSent: ok: step(response)
    IssuerCheckTransitionToOfferSent --> OfferCreated: no

    state OfferSent: remote message id
    state OfferSent: cred offer

    state IssuerCheckTransitionRequestReceived <<choice>>

    note left of IssuerCheckTransitionRequestReceived :  if transition allowed?

    OfferSent --> IssuerCheckTransitionRequestReceived: reply

    IssuerCheckTransitionRequestReceived --> RequestReceived: ok: step(cred request)
    IssuerCheckTransitionRequestReceived --> OfferSent: no
    IssuerCheckTransitionRequestReceived --> RequestRejected: step(cred reject)

    state RequestReceived: cred request

    RequestRejected --> Finished: cred reject

    state IssuerCheckTransitionToCredentialCreated <<choice>>

    note left of IssuerCheckTransitionToCredentialCreated :  if transition allowed?

    RequestReceived --> IssuerCheckTransitionToCredentialCreated: credential
    IssuerCheckTransitionToCredentialCreated --> CredentialCreated: ok: step(credential)
    IssuerCheckTransitionToCredentialCreated --> RequestReceived: no

    state CredentialCreated: credential

    state IssuerCheckTransitionToCredentialSent <<choice>>

    note left of IssuerCheckTransitionToCredentialSent :  if transition allowed?

    CredentialCreated --> IssuerCheckTransitionToCredentialSent: response
    IssuerCheckTransitionToCredentialSent --> CredentialSent: ok: step(response)
    IssuerCheckTransitionToCredentialSent --> CredentialCreated: no

    state CredentialSent: remote message id
    state CredentialSent: cred offer

  state IssuerCheckTransitionToFinish <<choice>>

  note left of IssuerCheckTransitionToFinish :  if transition allowed?

  CredentialSent --> IssuerCheckTransitionToFinish: credential ack
  IssuerCheckTransitionToFinish --> CredentialAckReceived: ok: step(credential ack)
  IssuerCheckTransitionToFinish --> CredentialSent: no

  state CredentialAckReceived

  CredentialAckReceived --> Finished

  state Finished

  Finished --> [*]

}

state Prover {
    [*] --> ProverInitialized

    state "Initialized" as ProverInitialized

    state ProverCheckTransitionToOfferCreated <<choice>>

    note left of ProverCheckTransitionToOfferCreated :  if transition allowed?

    ProverInitialized -down-> ProverCheckTransitionToOfferCreated: cred offer
    ProverCheckTransitionToOfferCreated -down-> OfferReceived: ok: step(cred offer)
    ProverCheckTransitionToOfferCreated -up-> ProverInitialized: no

    state OfferReceived: cred offer

    state ProverCheckTransitionToRequestCreated <<choice>>

    note left of ProverCheckTransitionToRequestCreated :  if transition allowed?

    OfferReceived --> ProverCheckTransitionToRequestCreated: cred request
    ProverCheckTransitionToRequestCreated --> RequestCreated: ok: step(cred request)
    ProverCheckTransitionToRequestCreated --> OfferReceived: no

    state RequestCreated: cred request

    state ProverCheckTransitionToRequestSent <<choice>>

    note left of ProverCheckTransitionToRequestSent :  if transition allowed?

    RequestCreated --> ProverCheckTransitionToRequestSent: response
    ProverCheckTransitionToRequestSent --> RequestSent: ok: step(response)
    ProverCheckTransitionToRequestSent --> RequestCreated: no

    state RequestSent: message id
    state RequestSent: cred request

    state ProverCheckTransitionToCredentialReceived <<choice>>

    note left of ProverCheckTransitionToCredentialReceived :  if transition allowed?

    RequestSent --> ProverCheckTransitionToCredentialReceived: credential
    ProverCheckTransitionToCredentialReceived --> CredentialReceived: ok: step(credential)
    ProverCheckTransitionToCredentialReceived --> RequestSent: no

    state CredentialReceived: credential

    state ProverCheckTransitionToCredentialAckCreated <<choice>>

    note left of ProverCheckTransitionToCredentialAckCreated :  if transition allowed?

    CredentialReceived --> ProverCheckTransitionToCredentialAckCreated: credential ack
    ProverCheckTransitionToCredentialAckCreated --> CredentialAckCreated: ok: step(credential ack)
    ProverCheckTransitionToCredentialAckCreated --> CredentialReceived: no

    state CredentialAckCreated: credential ack

    state ProverCheckTransitionToCredentialAckSent <<choice>>

    note left of ProverCheckTransitionToCredentialAckSent :  if transition allowed?

    CredentialAckCreated --> ProverCheckTransitionToCredentialAckSent: response
    ProverCheckTransitionToCredentialAckSent --> CredentialAckSent: ok: step(credential)
    ProverCheckTransitionToCredentialAckSent --> CredentialAckCreated: no

    state CredentialAckSent

    CredentialAckSent --> ProverFinished

    state "Finished" as ProverFinished

    ProverFinished --> [*]
}

@enduml