@startuml
skinparam ParticipantPadding 20
skinparam BoxPadding 20

title Credential Issuance
scale 0.9

box "Issuer" #LightBlue
actor "Issuer" as I
participant "State Machine" as ISM
participant "Libindy API" as ILA
participant "Message Family Helpers" as IH
endbox

box "Prover" #LightBlue
actor "Prover" as P
participant "State Machine" as PSM
participant "Libindy API" as PLA
participant "Message Family Helpers" as PH
endbox

I -[#blue]> ISM: <b> initialize
ISM -[#blue]-> ISM: state: <b> Initialized

P -[#blue]> PSM: <b> initialize
PSM -[#blue]-> PSM: state: <b> Initialized

I -[#grey]-> I: application logic
I -> ILA: <b> indy_issuer_create_credential_offer
ILA --> I: libindy cred_offer
I -[#grey]-> I: application logic
I -[#green]> IH: <b> prepare credential offer message
IH -[#blue]> ISM: <b> do step for credential offer message
ISM -[#blue]-> ISM: state: <b> CredentialOfferCreated
ISM -[#blue]-> I: credential offer message
I -[#grey]-> I: application logic
I -[#green]> P: <b> send credential offer message
I -[#grey]-> I: application logic

P -[#green]> PH: <b> parse message
P <-[#green]- PH: credential offer
P -[#grey]-> P: application logic
P -[#blue]> PSM: <b> check transition for credential offer
PSM -[#blue]-> P: is_transition_acceptable
P -[#blue]> PSM: <b> do step for credential offer
PSM -[#blue]-> PSM: state: <b> CredentialOfferReceived
P -> PLA: <b> prover_create_credential_request
PLA --> P: libindy cred_req
P -[#grey]-> P: application logic
P -[#green]> PH: <b> prepare credential request message
PH -[#blue]> PSM: <b> do step for credential request message
PSM -[#blue]-> PSM: state: <b> CredentialRequestCreated
PSM -[#blue]-> P: credential request message
P -[#grey]-> P: application logic
P -[#green]> I: <b> send credential request message
P -[#grey]-> P: application logic

I -[#green]> IH: <b> parse message
I <-[#green]- IH: credential request
I -[#grey]-> I: application logic
I -[#blue]> ISM: <b> check transition for credential request
ISM -[#blue]-> I: is_transition_acceptable
I -[#blue]> ISM: <b> do step for credential request
ISM -[#blue]-> ISM: state: <b> CredentialRequestReceived
I -[#grey]-> I: application logic
I -> ILA: <b> indy_issuer_create_credential
ILA --> I: libindy credential
I -[#grey]-> I: application logic
I -[#green]> IH: <b> prepare credential message
IH -[#blue]> ISM: <b> do step for credential message
ISM -[#blue]-> ISM: state: <b> CredentialCreated
ISM -[#blue]-> I: credential message
I -[#grey]-> I: application logic
I -[#green]> P: <b> send credential message
I -[#grey]-> I: application logic

P -[#green]> PH: <b> parse message
P <-[#green]- PH: credential
P -[#grey]-> P: application logic
P -[#blue]> PSM: <b> check transition for credential
PSM -[#blue]-> P: is_transition_acceptable
P -[#blue]> PSM: <b> do step for credential
PSM -[#blue]-> PSM: state: <b> CredentialReceived
P -> PLA: <b> indy_prover_store_credential
PLA --> P: uuid
P -[#grey]-> P: application logic
P -[#green]> PH: <b> prepare credential ack message
PH -[#blue]> PSM: <b> do step for credential ack message
PSM -[#blue]-> PSM: state: <b> CredentialAckCreated
PSM -[#blue]-> P:  credential ack message
P -[#grey]-> P: application logic
P -[#green]> I: <b> send credential ack message
P -[#grey]-> P: application logic
P -[#blue]> PSM: <b> do step
PSM -[#blue]-> PSM: state: <b> Finished
P -[#grey]-> P: application logic

I -[#green]> IH: <b> parse message
I <-[#green]- IH: credential ack message
I -[#grey]-> I: application logic
I -[#blue]> ISM: <b> check transition for credential ack message
ISM -[#blue]-> I: is_transition_acceptable
I -[#blue]> ISM: <b> do step for credential ack message
ISM -[#blue]-> ISM: state: <b> CredentialAckReceived
I -[#grey]-> I: application logic
I -[#blue]> ISM: <b> do step
ISM -[#blue]-> ISM: state: <b> Finished
I -[#grey]-> I: application logic

@enduml
