@startuml
title
 Credential API as Holder

 The diagram shows Credential object state transitions in case acting as a Holder.
end title

[*] --> VcxStateRequestReceived: vcx_credential_create_with_offer(CredentialOffer)

VcxStateRequestReceived --> VcxStateOfferSent: vcx_credential_send_request

note left of VcxStateOfferSent : use vcx_credential_update_state \n or vcx_credential_update_state_with_message \n for connection status updates

VcxStateOfferSent --> VcxStateAccepted: received `CRED` message

@enduml