# Development
FROM ubuntu:16.04

ARG uid=1000


# Update environment
# JRE installation and gcc
RUN apt-get update -y && apt-get install -y \
    gcc \
    pkg-config \
    build-essential \
    libsodium-dev \
    libssl-dev \
    libgmp3-dev \
    build-essential \
    libsqlite3-dev \
    libsqlite0 \
    cmake \
    apt-transport-https \
    ca-certificates \
    debhelper \
    wget \
    git \
    curl \
	libffi-dev \
    ruby \
    ruby-dev \ 
	sudo \
    rubygems 

# Install Nodejs 
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - \
    && apt-get install -y nodejs

RUN npm install typescript-compiler

# Install libindy
RUN mkdir -p /libindy
WORKDIR /libindy

ENV LIBINDY_DEB=libindy_1.1.0_amd64.deb
ENV LIBINDY_DOWNLOAD_URL=https://repo.sovrin.org/sdk/lib/apt/xenial/stable/$LIBINDY_DEB

RUN curl -fsOSL $LIBINDY_DOWNLOAD_URL \
    && dpkg -i $LIBINDY_DEB \
    && apt-get -f install

COPY libvcx/target/debug/libvcx.so /usr/lib/libvcx.so

RUN useradd -ms /bin/bash -u $uid vcx
USER vcx


