#!groovy

def rust
def vcx_python
def libindy
def vcx_nodejs

// ******** Artifacts Created ********
// libvcx_<ver>.deb (Debian Installable Library) ----> published Debian to https://repo.corp.evernym.com/deb/pool/main/libv/libvcx/
// vcx_<ver>.deb (Nodejs Wrapper Debian Package) ----> archived with Jenkins and Published to repo.corp.evernym.com/deb/pool
// vcx_<ver>.tgz (Nodejs Wrapper Npm Installable Package) ----> published with Filely to https://repo.corp.evernym.com/filely/npm/
// vcx_<ver>.tar.gz (Python Installable package) ----> archived with Jenkins
// ********* OTHERS ********
// DEPRECATED ( NO LONGER PRODUCED ) libvcx.tar.gz (libvcx.so file and provision_agent_keys.py) ----> archived with Jenkins

testing()

def testing() {
    stage('Testing') {
        parallel([
            'Main' : { mainUbuntu() },
            'Android': { android() },
            'iOS' : { ios() }
        ])
    }
}

def getUserUid() {
    return sh(returnStdout: true, script: 'id -u').trim()
}

def build(name, file, context='.', customParams = '') {
    return docker.build("$name", "${customParams} --build-arg uid=${getUserUid()} -f $file $context")
}

def mainUbuntu() {
    node('ubuntu') {
        stage('Main Build - Ubuntu') {
            def volumeName = "vcx-volume"
            def volumeInternalDir = "/sdk/vcx/output"
            try {
                checkout scm
                sh "docker volume rm -f $volumeName"

                // ******** Build the libindy base image (pulls down dependent debians from sovrin repo, and installs a majority of the dependencies)
                def libindy = docker.build("libindy", "-f vcx/ci/Dockerfile-libindy .")

                // ******** Build the libvcx base image (runs tests and creates debian automatically) ********
                def libvcx = docker.build("libvcx", "-f vcx/ci/Dockerfile-libvcx .")
                sh "docker run --rm -v $volumeName:$volumeInternalDir libvcx"
               
                // ******** Builds and tests the Node JS Wrapper *******
                def node = docker.build("node", "-f vcx/wrappers/node/ci/Dockerfile-nodejs-wrapper .")
                sh "docker run --rm -v $volumeName:$volumeInternalDir node"
                
                // ******** Builds and tests the Python Wrapper *******
                def python = docker.build("python", "-f vcx/wrappers/python3/ci/Dockerfile-python-wrapper .")    
                sh "docker run --rm -v $volumeName:$volumeInternalDir python"
                
                if (env.BRANCH_NAME == "master") {
                    // ******** PUBLISHING (artifacts are in a Docker Volume) ********
                    sh "docker build -t publish -f vcx/ci/Dockerfile-publish ."
                    withCredentials([usernameColonPassword(credentialsId: 'jenkins-kraken-svc', variable: 'KRAKEN_CREDENTIALS')]) {
                        def publish = docker.build('publish', "-f vcx/ci/Dockerfile-publish .")
                        publish.inside("--network=host -v $volumeName:$volumeInternalDir") {
                            // ******** Publish Libvcx Debian to repo ********
                            sh "/sdk/vcx/ci/scripts/publish.sh \"${KRAKEN_CREDENTIALS}\" \"libvcx*.deb\" https://kraken.corp.evernym.com/repo/portal_dev/upload"
                            sh "/sdk/vcx/ci/scripts/publish.sh \"${KRAKEN_CREDENTIALS}\" \"libvcx*.deb\" https://kraken.corp.evernym.com/repo/agency_dev/upload"
                            
                            // ******** Publish Npm Package to filely repo ********
                            sh "/sdk/vcx/ci/scripts/publish.sh \"${KRAKEN_CREDENTIALS}\" \"*.tgz\" https://kraken.corp.evernym.com/repo/npm/upload"
                 
                            // ******** Publish vcx Debian To Repo (NPM PACKAGES) 
                            sh "/sdk/vcx/ci/scripts/publish.sh \"${KRAKEN_CREDENTIALS}\" \"vcx_*.deb\" https://kraken.corp.evernym.com/repo/agency_dev/upload"
                            sh "/sdk/vcx/ci/scripts/publish.sh \"${KRAKEN_CREDENTIALS}\" \"vcx_*.deb\" https://kraken.corp.evernym.com/repo/portal_dev/upload"

                            // ******** Archive with Jenkins ********
                            sh "mkdir -p vcx/output"
                            sh "cp $volumeInternalDir/* vcx/output"
                            sh "ls $volumeInternalDir"
                            archiveArtifacts allowEmptyArchive: true, artifacts: 'vcx/output/*'

                        }
                    }
                }

            } catch (Exception ex) {
                currentBuild.result = "FAILED"
                if (env.BRANCH_NAME == "master") {
                    fail()
                }
                echo "$ex error"
            } finally {
				sh 'docker system df'
                sh "docker volume rm -f $volumeName"
                step([$class: 'WsCleanup'])
            }
        }
    }
}

def android() {
    node('ubuntu') {
        stage('Android Build') {
            try {
                checkout scm

                //Build android docker image
                rust = build('rust', 'vcx/ci/android.dockerfile', 'vcx')
                
                //Build .so files for arm64, x86, and arm
                buildAndroid(rust)

                //Package .so files into .aar 
                packageAndroid(rust)

                if (env.BRANCH_NAME == "master") {
                    //Publish package on aptly
                    publishAndroid(rust)
                }
            } catch (Exception ex) {
                // We currently do not fail the main build if the android and ios builds fai
                currentBuild.result = "FAILED"
                if (env.BRANCH_NAME == "master") {
                    fail()
                }
                echo "$ex error"
            } finally {
				sh 'docker system df'
                step([$class: 'WsCleanup'])
            }

        }
    }
}

def ios() {
    node('macos-vcx') {
        stage('iOS Build') {
            try {
                checkout scm
                SCRIPTS_PATH="vcx/libvcx/build_scripts/ios/mac"
                WORK_DIR = "/Users/jenkins"

                // Build ios architectures
                sh "source vcx/ci/scripts/iosBuild.sh"

                // Publish to Kraken

                if (env.BRANCH_NAME == "master") {
                    withCredentials([usernameColonPassword(credentialsId: 'jenkins-kraken-svc', variable: 'KRAKEN_CREDENTIALS')]) {
                        sh "find /Users/jenkins/IOSBuilds/libvcxpartial/ -type f -name 'vcx.libvcxpartial_*_universal.zip' -exec curl -u \"${KRAKEN_CREDENTIALS}\" -X POST  https://kraken.corp.evernym.com/repo/ios/upload -F 'file=@{}' \\;"
                        sh "find /Users/jenkins/IOSBuilds/libvcxall/ -type f -name 'vcx.libvcxall_*_universal.zip' -exec curl -u \"${KRAKEN_CREDENTIALS}\" -X POST  https://kraken.corp.evernym.com/repo/ios/upload -F 'file=@{}' \\;"
                    }
                }
            } catch (Exception ex) {
                // We currently do not fail the main build if the android and ios builds fail
                currentBuild.result = "FAILED"
                if (env.BRANCH_NAME == "master") {
                    fail()
                }
                echo "$ex error"
            } finally {
                step([$class: 'WsCleanup'])
            }

        }
    }
}

def fail() {
    def message = [
        message: "$JOB_NAME - Build # $BUILD_NUMBER - fail: Check console output at $BUILD_URL to view the results."
    ]
    slackSend message
}

def buildAndroid(envn) {
    envn.inside {
        LIBINDY_BRANCH="stable"
        LIBINDY_VERSION="1.6.1"
        LIBINDY_TAG=""
        LIBNULLPAY_BRANCH="stable"
        LIBNULLPAY_VERSION="1.6.1"
        LIBNULLPAY_TAG=""

        ANDROID_SCRIPT_PATH = 'vcx/ci/scripts/androidBuild.sh'
        sh "LIBINDY_BRANCH=${LIBINDY_BRANCH} LIBINDY_VERSION=${LIBINDY_VERSION} LIBNULLPAY_BRANCH=${LIBNULLPAY_BRANCH} LIBNULLPAY_VERSION=${LIBNULLPAY_VERSION} ./${ANDROID_SCRIPT_PATH} arm64"
        sh "LIBINDY_BRANCH=${LIBINDY_BRANCH} LIBINDY_VERSION=${LIBINDY_VERSION} LIBNULLPAY_BRANCH=${LIBNULLPAY_BRANCH} LIBNULLPAY_VERSION=${LIBNULLPAY_VERSION} ./${ANDROID_SCRIPT_PATH} arm"
        sh "LIBINDY_BRANCH=${LIBINDY_BRANCH} LIBINDY_VERSION=${LIBINDY_VERSION} LIBNULLPAY_BRANCH=${LIBNULLPAY_BRANCH} LIBNULLPAY_VERSION=${LIBNULLPAY_VERSION} ./${ANDROID_SCRIPT_PATH} x86"
//        sh "LIBINDY_BRANCH=${LIBINDY_BRANCH} LIBINDY_VERSION=${LIBINDY_VERSION} LIBNULLPAY_BRANCH=${LIBNULLPAY_BRANCH} LIBNULLPAY_VERSION=${LIBNULLPAY_VERSION} ./${ANDROID_SCRIPT_PATH} arm64"
        //Todo: get parallel processing to work. Currently it fails on Jenkins. It must share files or something
        // parallel([
        //     'arm': { sh "./${ANDROID_SCRIPT_PATH} arm"},
        //     'x86': { sh "./${ANDROID_SCRIPT_PATH} x86"},
        //     'arm64': { sh "./${ANDROID_SCRIPT_PATH} arm64"}
        // ])
    }
}

def packageAndroid(envn) {
    envn.inside {
        ANDROID_SCRIPT_PATH = 'vcx/ci/scripts/androidPackage.sh'
        sh "chmod +x ${ANDROID_SCRIPT_PATH}"
        sh "./${ANDROID_SCRIPT_PATH}"
    }
}

def publishAndroid(envn) {
    envn.inside {
        withCredentials([file(credentialsId: 'cloudrepo-artifactory-settings-libvcx', variable: 'settingsFile')]) {
            sh 'cp $settingsFile .'
            ANDROID_SCRIPT_PATH = 'vcx/ci/scripts/androidPublish.sh'
            sh "chmod +x ${ANDROID_SCRIPT_PATH}"
            sh "./${ANDROID_SCRIPT_PATH}"
        }
    }
}
