@startuml
title
 IssuerCredential API as Issuer

 The diagram shows IssuerCredential object state transitions in case acting as an Issuer.
end title

[*] --> VcxStateInitialized: vcx_issuer_create_credential

VcxStateInitialized --> VcxStateOfferSent: vcx_issuer_send_credential_offer

note left of VcxStateOfferSent : use vcx_issuer_credential_update_state \n or vcx_issuer_credential_update_state_with_message \n for connection status updates

VcxStateOfferSent --> VcxStateRequestReceived: received `CredentialRequest` message
VcxStateOfferSent --> VcxStateNone: received `ProblemReport` message

VcxStateRequestReceived --> VcxStateAccepted: vcx_issuer_send_credential

note left of VcxStateAccepted : use vcx_issuer_credential_update_state \n or vcx_issuer_credential_update_state_with_message \n for connection status updates

VcxStateAccepted --> VcxStateAccepted: received `Ack` message

@enduml