pub const NODE: &'static str = "0";
pub const NYM: &'static str = "1";
pub const ATTRIB: &'static str = "100";
pub const SCHEMA: &'static str = "101";
pub const CLAIM_DEF: &'static str = "102";
pub const GET_ATTR: &'static str = "104";
pub const GET_NYM: &'static str = "105";
pub const GET_TXN: &'static str = "3";
pub const GET_SCHEMA: &'static str = "107";
pub const GET_CLAIM_DEF: &'static str = "108";
pub const POOL_UPGRADE: &'static str = "109";
pub const POOL_CONFIG: &'static str = "111";
pub const GET_DDO: &'static str = "120";//TODO change number

pub const STEWARD: &str = "2";
pub const TRUSTEE: &str = "0";
pub const TRUST_ANCHOR: &str = "101";
pub const TGB: &str = "100";
pub const ROLE_REMOVE: &str = "";
